apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev-products-ns
    server: https://kubernetes.default.svc
  source:
    path: products
    repoURL: https://github.com/adhithia21/argocd-batch-14.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true