apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: 10Mi
            cpu: 10m
        ports:
        - containerPort: 80
